# Generated by Django 3.0.8 on 2020-10-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201026_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='AField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('file', models.FileField(upload_to='additional_fields')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afield', to='blog.Post')),
            ],
        ),
    ]
