# Generated by Django 3.0.8 on 2020-10-31 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201031_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='header',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='headers'),
            preserve_default=False,
        ),
    ]
